<definitions name="MyService"
    targetNamespace="http://example.com/wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://example.com/wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <message name="GetWordsRequest">
        <part name="text" type="xds:string"/>
    </message>
    <message name="GetWordsResponse">
        <part name="result" type="xds:string"/>
    </message>
    <portType name="Port">
        <operation name="GetWords">
            <input message="tns:GetWordsRequest"/>
            <output message="tns:GetWordsResponse"/>
        </operation>
    </portType>
    <binding name="Binding" type="tns:Port">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetWords">
            <soap:operation soapAction="http://example.com/wsdl#Calculate"/>
            <input>
                <soap:body use="encoded" namespace="http://example.com/wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded" namespace="http://example.com/wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
    <service name="Service">
        <port name="Port" binding="tns:Binding">
            <soap:address location="http://localhost:8001/words"/>
        </port>
    </service>
</definitions>
